[package]
name = "url-transport"
version = "1.0.0"
authors = ["jonah"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.4.10" }
url = "2.2.2"
redis = "0.21.5"
